### ISSUE TITLE
The example is confusing

### ISSUE THREAD

**Issue by petrillek** [localgovdrupal/localgov_keynav#4]
Hi Marky,
nice module.
I think I found a tiny bug in a field description.
There is `Do not include the lgd part.` on line [66](https://github.com/localgovdrupal/localgov_keynav/blob/1.x/src/Form/SettingsForm.php), but the following example includes it.
So the resulting shortcut would be `lgdlgdnews` if I understand it correctly.

**Comment by markconroy** [comment]
Thanks @petrillek 

That is fixed now in #6 and available in release 1.0.1

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.
